### ISSUE TITLE
Article harvesting (sections and l1= problems)

### ISSUE THREAD

**Issue by mikima** [densitydesign/strumentalia-mainology#1]
The "main article" template accepts parameters, not only wiki-links.
See: https://en.wikipedia.org/wiki/Template:Main#Parameters

Therefore, to properly get links, mainology should:

1) trim away what's after # symbol
2) filter all the labels parameters (identified by "l1=", "l2=" etc). A possible regexp could be: ^l.=

**Comment by fenicento** [comment]
done in 0e772fd20278540448d4594064e8dbc78257212b
